# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_auto_20160828_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0430\u0432\u0442\u043e\u0441\u0435\u0440\u0432\u0438\u0441\u0430')),
                ('phone', models.PositiveIntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('address', models.CharField(max_length=250, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('about', models.TextField(max_length=1000, verbose_name='\u041e\u0431 \u0430\u0432\u0442\u043e\u0441\u0435\u0440\u0432\u0438\u0441\u0435')),
                ('site', models.CharField(max_length=50, unique=True, verbose_name='\u0421\u0430\u0439\u0442')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440 \u0430\u0432\u0442\u043e\u0441\u0435\u0440\u0432\u0438\u0441\u0430')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430')),
                ('breakdown', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.Breakdown', verbose_name='\u041f\u043e\u043b\u043e\u043c\u043a\u0430')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='works',
            field=models.ManyToManyField(to='services.Work', verbose_name='\u0412\u0438\u0434\u044b \u0440\u0430\u0431\u043e\u0442 \u0438 \u0446\u0435\u043d\u044b'),
        ),
    ]
