# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '\u0410\u0432\u0442\u043e\u0441\u0435\u0440\u0432\u0438\u0441', 'verbose_name_plural': '\u0410\u0432\u0442\u043e\u0441\u0435\u0440\u0432\u0438\u0441\u044b'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '\u0420\u0430\u0431\u043e\u0442\u0430-\u0446\u0435\u043d\u0430', 'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0442\u044b-\u0446\u0435\u043d\u044b'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='works',
        ),
        migrations.AddField(
            model_name='work',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='\u0410\u0432\u0442\u043e\u0441\u0435\u0440\u0432\u0438\u0441'),
        ),
    ]
