# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20160828_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='about',
            field=models.TextField(blank=True, max_length=1000, verbose_name='\u041e\u0431 \u0430\u0432\u0442\u043e\u0441\u0435\u0440\u0432\u0438\u0441\u0435'),
        ),
        migrations.AlterField(
            model_name='service',
            name='site',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='work',
            name='breakdown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Breakdown', verbose_name='\u041f\u043e\u043b\u043e\u043c\u043a\u0430'),
        ),
    ]
