# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20160828_1555'),
        ('services', '0005_auto_20160910_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.CarBrand', verbose_name='\u041c\u0430\u0440\u043a\u0430 \u043c\u0430\u0448\u0438\u043d\u044b'),
        ),
    ]
