# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='node',
            name='root',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breakdown_search.InstructionStep'),
        ),
        migrations.AlterField(
            model_name='node',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breakdown_search.Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breakdown_search.InstructionStep'),
        ),
    ]
