# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown_search', '0003_node_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='answer_text',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
