# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20160828_1555'),
        ('breakdown_search', '0005_auto_20160912_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='breakdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Breakdown'),
        ),
    ]
