# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown_search', '0006_node_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionstep',
            name='next_step',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breakdown_search.InstructionStep'),
        ),
    ]
