# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20160828_1555'),
        ('breakdown_search', '0007_auto_20160912_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='breakdown',
        ),
        migrations.AddField(
            model_name='node',
            name='breakdowns',
            field=models.ManyToManyField(blank=True, null=True, to='cars.Breakdown'),
        ),
    ]
