# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown_search', '0008_auto_20160912_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionstep',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
