# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown_search', '0009_instructionstep_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u043e\u043c\u043a\u0443, \u0435\u0441\u043b\u0438 \u043f\u0440\u043e\u0431\u0435\u0433 \u0431\u043e\u043b\u044c\u0448\u0435'),
        ),
        migrations.AddField(
            model_name='node',
            name='root_nodes',
            field=models.ManyToManyField(blank=True, related_name='_node_root_nodes_+', to='breakdown_search.Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='answer_text',
            field=models.CharField(blank=True, max_length=250, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435 \u043e\u0442\u0432\u0435\u0442\u0430 \u0443 \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u043e\u0439 \u043d\u043e\u0434\u044b'),
        ),
        migrations.AlterField(
            model_name='node',
            name='breakdowns',
            field=models.ManyToManyField(blank=True, to='cars.Breakdown', verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u0432\u043e\u0437\u043c\u043e\u0436\u043d\u044b\u0445 \u043f\u043e\u043b\u043e\u043c\u043e\u0433'),
        ),
        migrations.AlterField(
            model_name='node',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.CarModel', verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u043c\u0430\u0448\u0438\u043d\u044b, \u043d\u0430 \u043a\u043e\u0442\u043e\u0440\u0443\u044e \u0437\u0430\u0432\u044f\u0437\u0430\u043d\u0430 \u043d\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='node',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breakdown_search.InstructionStep', verbose_name='\u041f\u0435\u0440\u0432\u044b\u0439 \u0448\u0430\u0433 \u0438\u043d\u0441\u0442\u0440\u0443\u043a\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u043e\u0434\u044b'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u043e\u0434\u044b'),
        ),
        migrations.AlterField(
            model_name='node',
            name='root',
            field=models.BooleanField(default=False, verbose_name='\u041a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u043b\u0438 \u043d\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='node',
            name='root_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_node', to='breakdown_search.Node', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0430\u044f \u043d\u043e\u0434\u0430'),
        ),
    ]
