# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown_search', '0011_auto_20160921_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='root_node',
        ),
    ]
