# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdown_search', '0014_auto_20160921_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='need_select',
            field=models.BooleanField(default=False, verbose_name='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0434\u043b\u044f \u043e\u0442\u0432\u0435\u0442\u043e\u0432 \u0432 \u0432\u0435\u0440\u0441\u0442\u043a\u0435 \u0441\u0435\u043b\u0435\u043a\u0442'),
        ),
    ]
