# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u043e\u043b\u043e\u043c\u043a\u0438')),
                ('difficulty', models.IntegerField(choices=[(0, '\u041b\u0435\u0433\u043a\u043e'), (1, '\u0421\u0440\u0435\u0434\u043d\u0435'), (2, '\u0421\u043b\u043e\u0436\u043d\u043e')], default=0, verbose_name='\u0421\u043b\u043e\u0436\u043d\u043e\u0441\u0442\u044c \u043f\u043e\u043b\u043e\u043c\u043a\u0438')),
                ('jobs_types', models.TextField(blank=True, max_length=1000, verbose_name='\u0412\u0438\u0434\u044b \u0440\u0430\u0431\u043e\u0442')),
                ('spares', models.TextField(blank=True, max_length=250, verbose_name='\u0417\u0430\u043f\u0447\u0430\u0441\u0442\u0438')),
                ('symptoms', models.TextField(blank=True, max_length=1000, verbose_name='\u0421\u0438\u043c\u043f\u0442\u043e\u043c\u044b')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043b\u043e\u043c\u043a\u0430',
                'verbose_name_plural': '\u041f\u043e\u043b\u043e\u043c\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='BreakdownType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0422\u0438\u043f \u043f\u043e\u043b\u043e\u043c\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u043f\u043e\u043b\u043e\u043c\u043a\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043f\u043e\u043b\u043e\u043c\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043c\u0430\u0440\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u041c\u0430\u0440\u043a\u0438 \u043c\u0430\u0448\u0438\u043d\u044b',
                'verbose_name_plural': '\u041c\u0430\u0440\u043a\u0438 \u043c\u0430\u0448\u0438\u043d',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043c\u043e\u0434\u0435\u043b\u0438 \u043c\u0430\u0448\u0438\u043d\u044b')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarBrand', verbose_name='\u041c\u0430\u0440\u043a\u0430 \u043c\u0430\u0448\u0438\u043d\u044b')),
            ],
            options={
                'verbose_name': '\u041c\u043e\u0434\u0435\u043b\u044c \u043c\u0430\u0448\u0438\u043d\u044b',
                'verbose_name_plural': '\u041c\u043e\u0434\u0435\u043b\u0438 \u043c\u0430\u0448\u0438\u0438\u043d',
            },
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.IntegerField(choices=[(0, 'gasoline'), (1, 'diesel'), (2, 'hybrid'), (3, 'electric')], default=0, verbose_name='\u0422\u0438\u043f \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f')),
                ('transmission_type', models.IntegerField(choices=[(0, 'MT'), (1, 'AT'), (2, 'AMT'), (3, 'CVT')], default=0, verbose_name='\u0422\u0438\u043f \u0442\u0440\u0430\u043d\u0441\u043c\u0438\u0441\u0441\u0438\u0438')),
                ('engine_volume', models.IntegerField(blank=True, null=True, verbose_name='\u041e\u0431\u044a\u0435\u043c \u0434\u0432\u0438\u0433\u0430\u0442\u0435\u043b\u044f')),
                ('horsepower', models.IntegerField(blank=True, null=True, verbose_name='\u041b\u043e\u0448\u0430\u0434\u0438\u043d\u044b\u0435 \u0441\u0438\u043b\u044b')),
                ('drive', models.IntegerField(choices=[(0, 'front'), (1, 'rear'), (2, 'all')], default=0, verbose_name='\u0422\u0438\u043f \u043f\u0440\u0438\u0432\u043e\u0434\u0430')),
                ('year', models.IntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], null=True, verbose_name='\u0413\u043e\u0434 \u0432\u044b\u043f\u0443\u0441\u043a\u0430')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarModel', verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u043c\u0430\u0448\u0438\u043d\u044b')),
            ],
            options={
                'verbose_name': '\u041c\u043e\u0434\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f \u043c\u0430\u0448\u0438\u043d\u044b',
                'verbose_name_plural': '\u041c\u043e\u0434\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438 \u043c\u0430\u0448\u0438\u043d',
            },
        ),
        migrations.AddField(
            model_name='breakdown',
            name='breakdown_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.BreakdownType', verbose_name='\u0422\u0438\u043f \u043f\u043e\u043b\u043e\u043c\u043a\u0438'),
        ),
    ]
