# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20160828_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='show_services',
            field=models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0430\u0432\u0442\u043e\u0441\u0435\u0440\u0432\u0438\u0441\u044b'),
        ),
    ]
